In [2]:
import numpy as np

In [3]:
#1
array_1d = np.arange(10)
print("1D Array:", array_1d)

1D Array: [0 1 2 3 4 5 6 7 8 9]


In [4]:
#2
array_2d = np.random.randint(1, 21, size=(3, 3))
print("2D Array:\n", array_2d)

2D Array:
 [[ 7  7 18]
 [10  5 20]
 [ 6 11 16]]


In [5]:
#3
array_3d = np.ones((2, 3, 4))
print("3D Array:\n", array_3d)

3D Array:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [6]:
#4
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
sum_arrays = np.add(array_a, array_b)
print("Element-wise Sum:", sum_arrays)

Element-wise Sum: [5 7 9]


In [7]:
#5
array_c = np.array([[1, 2, 3], [4, 5, 6]])
array_d = np.array([[7, 8, 9], [10, 11, 12]])
product_arrays = np.multiply(array_c, array_d)
print("Element-wise Product:\n", product_arrays)

Element-wise Product:
 [[ 7 16 27]
 [40 55 72]]


In [8]:
#6
dot_product = np.dot(array_c, array_d.T)
print("Dot Product:\n", dot_product)

Dot Product:
 [[ 50  68]
 [122 167]]


In [9]:
#7
mean_value = np.mean(array_1d)
median_value = np.median(array_1d)
std_deviation = np.std(array_1d)
print("Mean:", mean_value, "Median:", median_value, "Standard Deviation:", std_deviation)

Mean: 4.5 Median: 4.5 Standard Deviation: 2.8722813232690143


In [10]:
#8
max_value = np.max(array_2d)
min_value = np.min(array_2d)
print("Max Value:", max_value, "Min Value:", min_value)

Max Value: 20 Min Value: 5


In [13]:
#9
normal_dist = np.random.normal(0, 1, 1000)
print("Normal Distribution Array (first 10):", normal_dist[:10])

Normal Distribution Array (first 10): [-0.82001269 -1.43722231 -0.2874587  -0.55237204 -0.25928776  0.88407157
  0.19727292  1.23791207 -0.87134617  0.07915186]


In [14]:
#10
uniform_dist_2d = np.random.randint(10, 51, size=(5, 5))
print("2D Array from Uniform Distribution:\n", uniform_dist_2d)

2D Array from Uniform Distribution:
 [[17 42 48 48 24]
 [25 34 21 34 15]
 [27 29 34 24 28]
 [39 11 23 21 15]
 [23 14 50 38 31]]


In [17]:
#11
cumsum_array = np.cumsum(array_1d)
print("Cumulative Sum:", cumsum_array)

Cumulative Sum: [ 0  1  3  6 10 15 21 28 36 45]


In [18]:
#12
corr_coeff_matrix = np.corrcoef(array_2d)
print("Correlation Coefficient Matrix:\n", corr_coeff_matrix)

Correlation Coefficient Matrix:
 [[1.         0.94491118 0.8660254 ]
 [0.94491118 1.         0.65465367]
 [0.8660254  0.65465367 1.        ]]


In [19]:
#13
dice_rolls = np.random.randint(1, 7, 1000)
roll_counts = np.bincount(dice_rolls)[1:]
print("Dice Roll Frequencies:", roll_counts)

Dice Roll Frequencies: [192 170 167 158 164 149]
