### Linear Algebra Tasks



In [3]:
import numpy as np

# Task 1: Create a zero matrix
A = np.zeros((3, 3))
print(A)

# Task 2: Create an identity matrix
I = np.eye(3)
print(I)

# Task 3: Create a random matrix
A = np.random.rand(3, 3)
print(A)

# Task 4: Basic matrix operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A + B
print(C)
D = A - B
print(D)
E = np.dot(A, B)
print(E)

# Task 5: Transpose a matrix
A = np.array([[1, 2], [3, 4]])
At = A.T
print(At)

# Task 6: Find the determinant and inverse of a matrix
A = np.array([[1, 2], [3, 4]])
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
print("Determinant:", det_A)
print("Inverse:", inv_A)

# Task 7: Solve a system of linear equations
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print(x)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.9172646  0.69984174 0.25343776]
 [0.26702347 0.45866153 0.4592166 ]
 [0.98560287 0.68435323 0.35603857]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
Determinant: -2.0000000000000004
Inverse: [[-2.   1. ]
 [ 1.5 -0.5]]
[-4.   4.5]


### Vector Operations



In [4]:
# Task 11: Basic vector operations (addition, dot product, cross product)
v1 = np.array([1, 2])
v2 = np.array([3, 4])
v_sum = v1 + v2
v_dot_product = np.dot(v1, v2)
v_cross_product = np.cross(v1, v2)
print(v_sum)
print(v_dot_product)
print(v_cross_product)


[4 6]
11
-2


In [5]:

# Task: Normalize a vector and compute vector norms
v1 = np.array([1, 2])
norm_v1 = np.linalg.norm(v1)
normalized_v1 = v1 / norm_v1
print(norm_v1)
print(normalized_v1)


2.23606797749979
[0.4472136  0.89442719]


### Calculus Tasks
- Numerical Differentiation




In [6]:
# Compute the numerical derivative of a given function
def f(x):
    return x**2 + np.sin(x)

def numerical_derivative(f, x, h=1e-6):
    return (f(x + h) - f(x)) / h


x = 1.0
derivative = numerical_derivative(f, x)
print(f'Numerical derivative at x={x}: {derivative}')

Numerical derivative at x=1.0: 2.54030288515672


- Numerical Integration


In [8]:
# Compute the numerical integral of a given function
def f(x):
    return np.sin(x)

def numerical_integral(f, a, b, method='trapezoidal', N=1000):
    x = np.linspace(a, b, N)
    dx = (b - a) / N
    
    if method == 'trapezoidal':
        integral = np.trapz(f(x), x)
    elif method == 'simpson':
        integral = np.sum(dx / 3 * (f(x[0]) + 4*f(x[1:-1:2]).sum() + 2*f(x[2:-2:2]).sum() + f(x[-1])))
    else:
        raise ValueError(f'Method {method} is not supported.')

    return integral


a, b = 0, np.pi
integral_trapezoidal = numerical_integral(f, a, b, method='trapezoidal')
integral_simpson = numerical_integral(f, a, b, method='simpson')

print(f'Numerical integral using Trapezoidal rule: {integral_trapezoidal}')
print(f'Numerical integral using Simpson\'s rule: {integral_simpson}')


Numerical integral using Trapezoidal rule: 1.999998351770852
Numerical integral using Simpson's rule: 1.9979917671073473


- Partial Derivatives


In [10]:
# Calculate partial derivatives of multivariable functions
def f(x, y):
    return x**2 + y**3

def partial_derivative(f, var='x', point=(1, 2), h=1e-6):
    if var == 'x':
        return (f(point[0] + h, point[1]) - f(point[0], point[1])) / h
    elif var == 'y':
        return (f(point[0], point[1] + h) - f(point[0], point[1])) / h
    else:
        raise ValueError(f'Variable {var} is not supported.')

# Example usage
partial_x = partial_derivative(f, var='x', point=(1, 2))
partial_y = partial_derivative(f, var='y', point=(1, 2))

print(f'Partial derivative with respect to x: {partial_x}')
print(f'Partial derivative with respect to y: {partial_y}')


Partial derivative with respect to x: 2.0000010003684565
Partial derivative with respect to y: 12.000006002210739


In [11]:
from scipy.optimize import minimize

# Solve optimization problems with constraints
def objective(x):
    return x[0]**2 + x[1]**2

def constraint(x):
    return x[0] + x[1] - 1

x0 = [0.5, 0.5]  # Initial guess
bounds = ((-1, 1), (-1, 1))  # Bounds for variables
constraint_obj = {'type': 'eq', 'fun': constraint}  # Constraint definition

result = minimize(objective, x0, bounds=bounds, constraints=constraint_obj)

print(f'Optimal solution: {result.x}')


Optimal solution: [0.5 0.5]
