In [2]:
import numpy as np

In [3]:
#1
array_2d_5x5 = np.random.randint(1, 21, (5, 5))
sub_array_3x3 = array_2d_5x5[1:4, 1:4]
print("3x3 Sub-array:\n", sub_array_3x3)

3x3 Sub-array:
 [[ 5  6 18]
 [ 2 10 11]
 [ 8  6 12]]


In [4]:
#2
array_3d_4x3x2 = np.random.randint(1, 21, (4, 3, 2))
sub_array_3d = array_3d_4x3x2[:2, :, 1]
print("Extracted elements from 3D array:\n", sub_array_3d)

Extracted elements from 3D array:
 [[20 16  2]
 [12 12 11]]


In [5]:
#3
array_int = np.array([0, 5, 10, 15, 20, 25, 30, 35, 40])
fancy_indexed = array_int[[1, 3, 4, 7]]
print("Fancy indexed elements:", fancy_indexed)

Fancy indexed elements: [ 5 15 20 35]


In [6]:
#4
array_2d = np.random.randint(1, 21, (4, 5))
fancy_indexed_2d = array_2d[[0, 2, 3]][:, [1, 3]]
print("Fancy indexed 2D array:\n", fancy_indexed_2d)

Fancy indexed 2D array:
 [[17  6]
 [ 5 17]
 [ 3 12]]


In [7]:
#5
array_1d_random = np.random.randint(1, 20, 10)
greater_than_10 = array_1d_random[array_1d_random > 10]
print("Elements greater than 10:", greater_than_10)

Elements greater than 10: [17 15 19 14 11]


In [8]:
#6
array_2d_5x5[array_2d_5x5 > 15] = 0
print("Array with elements > 15 replaced by 0:\n", array_2d_5x5)

Array with elements > 15 replaced by 0:
 [[ 1  0 15  0  8]
 [ 0  5  6  0  9]
 [ 7  2 10 11  0]
 [ 7  8  6 12  4]
 [ 0  0  6  7  2]]


In [22]:
#7
array_1d_3 = np.array([1, 2, 3])
array_2d_4x3 = np.random.randint(1, 10, (4, 3))
broadcasted_sum = array_2d_4x3 + array_1d_3
print("Broadcasted addition:\n", broadcasted_sum)

Broadcasted addition:
 [[ 2  4  9]
 [ 9 11 10]
 [ 8  7  9]
 [ 6  3  8]]


In [21]:
#8
array_2d_3x3 = np.random.randint(1, 10, (3, 3))
array_1d_3 = np.array([2, 4, 6])
broadcasted_product = array_2d_3x3 * array_1d_3
print("Broadcasted multiplication:\n", broadcasted_product)

Broadcasted multiplication:
 [[10 36 48]
 [12 16 48]
 [ 2  4 48]]


In [20]:
#9
array_2d_3x1 = np.array([[1], [2], [3]])
array_2d_1x4 = np.array([[10, 20, 30, 40]])
element_wise_sum = array_2d_3x1 + array_2d_1x4
print("Element-wise addition:\n", element_wise_sum)     

Element-wise addition:
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [19]:
#10
array_3d_2x3x4 = np.random.randint(1, 10, (2, 3, 4))
array_2d_3x4 = np.random.randint(1, 10, (3, 4))
broadcasted_3d = array_3d_2x3x4 + array_2d_3x4
print("Broadcasted addition in 3D:\n", broadcasted_3d)

Broadcasted addition in 3D:
 [[[11 15  9 16]
  [11 11 10 13]
  [ 9 12  9 15]]

 [[ 4  8  7 10]
  [17 12 14 14]
  [16 14  7 10]]]


In [23]:
#11
array_2d_6x6 = np.random.randint(1, 20, (6, 6))
sliced_array = array_2d_6x6[::2, ::2]
array_1d_for_addition = np.array([1, 2, 3])
sliced_with_addition = sliced_array + array_1d_for_addition
print("Sliced and added array:\n", sliced_with_addition)


Sliced and added array:
 [[ 8  7 21]
 [ 6 11 15]
 [ 3 11 11]]


In [34]:
#12
import numpy as np
array_2d = np.random.randint(1, 20, (6, 6))
sliced_array = array_2d[::2, ::2]
array_1d = np.array([1, 2, 3])
result = sliced_array + array_1d

print("Original Array:\n", array_2d)
print("Sliced Array:\n", sliced_array)
print("Result after adding 1D array:\n", result)

Original Array:
 [[ 7 13 14 14  6  1]
 [ 4 18 16 18  9 13]
 [17  8 16 13  4 11]
 [ 3  8 10  9  1 12]
 [12 12 15 18 15 16]
 [18  4  7 18 15  5]]
Sliced Array:
 [[ 7 14  6]
 [17 16  4]
 [12 15 15]]
Result after adding 1D array:
 [[ 8 16  9]
 [18 18  7]
 [13 17 18]]


In [27]:
#13
diagonal_elements = np.diagonal(array_2d)
print("Diagonal elements:", diagonal_elements)

Diagonal elements: [15 19  9 12]


In [28]:
#14
reversed_array_2d = array_2d[:, ::-1]
print("Reversed rows:\n", reversed_array_2d)

Reversed rows:
 [[15  6 16 17 15]
 [15 13 14 19  6]
 [ 4 17  9  5 17]
 [ 5 12 18  3 20]]


In [29]:
#15
array_3d_7x6x5 = np.random.randint(1, 20, (7, 6, 5))
sub_array_2x3x4 = array_3d_7x6x5[:2, :3, :4]
array_1d_for_broadcast = np.array([1, 2, 3, 4])
added_broadcast = sub_array_2x3x4 + array_1d_for_broadcast[np.newaxis, np.newaxis, :]
print("Sub-array with broadcasting:\n", added_broadcast)


Sub-array with broadcasting:
 [[[15 13 16 21]
  [10 17 19 14]
  [16  8  6 17]]

 [[13 10  4  5]
  [17 19 16 22]
  [20 17  4 17]]]


In [30]:
#16
array_2d_for_last = np.random.randint(1, 10, (5, 3))
array_2d_for_last[:, -1] = array_2d_for_last[:, 0] + array_2d_for_last[:, 1]
print("Modified 2D array:\n", array_2d_for_last)

Modified 2D array:
 [[ 6  4 10]
 [ 9  1 10]
 [ 4  4  8]
 [ 9  1 10]
 [ 9  9 18]]
